[package]
name = "ds"
version = "1.1.0"
edition = "2024"

[dependencies]
users = "0.11"
clap = { version = "4.5.41", features = ["derive"] }
owo-colors = "4.2.2"
strum = { version = "0.27.2", features = ["derive"] }
strum_macros = "0.27"
tabled = "0.20.0"
chrono = "0.4.41"
